### ISSUE TITLE
Gateway needs to retain extension data from federated services

### ISSUE THREAD

**Issue by dragonfriend0013** [mercurius-js/mercurius-gateway#29]
I have a need to retain any/specific extension data returned from a downstream federated service.  Is there a current pattern for doing this?  Looking at the code, this appears to not be possible currently.  I belive that this could be accomplished with a hook, or by placing this data into the gateways context so that the onResolution hook could be used to process those extensions

**Comment by marco-ippolito** [comment]
This feature has been introduced with  [extension collectors](https://github.com/mercurius-js/mercurius-gateway#collectors).
