### ISSUE TITLE
Federation not fetching downstream simple query result type `Int`

### ISSUE THREAD

**Issue by tomi-bigpi** [mercurius-js/mercurius-gateway#33]
I ran into an issue with a federated query that simply returns an `Int`. Calling the service directly (also running on Mercurius) returns the value as expected.

Relevant bit from the schema:
```graphql
type Query {
  myCount: Int!
}
```

I'm not seeing any calls from the federation service to the downstream service, and calls fail with `Cannot return null for non-nullable field Query.myCount.`. Making the return type nullable causes a `null` to be returned.

Wrapping the result in a custom type, such as `type MyAggregations { count: Int! }` works as expected.

**Comment by codeflyer** [comment]
I've created a test file for this issue: https://github.com/mercurius-js/mercurius-gateway/pull/43

It seems to work properly.

**Comment by MrSaints** [comment]
I know there's a test for it, but this still seems to be an issue when used with Python's Graphene Federation. It works fine using Apollo Federation / Gateway.
